Feature/0.2.0 (#59)
* Completely redesigned bot architecture

* Added CI for this branch. Branch: [feature/2.0.0](https://github.com/orenlab/pytmbot/tree/feature/2.0.0)

* Added CI for this branch. Branch: [feature/2.0.0](https://github.com/orenlab/pytmbot/tree/feature/2.0.0)

* Update docs

* Bump version

* Fix some methods request

* Minor change in build process.

* I'm starting to add in-line handlers. I'll start with the swap_info function.

* Deleted the unnecessary import of the docker package

* Make StateFabric class private

* Added update_info inline handler

* Encapsulated critical methods

* Completed the transfer of inline handlers to the new architecture.

* Debugging techniques for container management

* Fix link in docs

* Added buttons to switch to the requested function after successful authentication. There are also some cosmetic improvements.

* Update Dockerfile

* Added docstring

* Fix some errors and bump the version number to Alpha 2.

* Update docs for 0.2.0

* The bot configuration has been converted to the YAML format.

* Delete pytmbot.yaml

* Delete outline.yaml

* An information security incident has occurred. All tokens have been canceled.

* Added support for generating "salt" for the bot config

* Added support for generating "salt" for the bot config

* Launching the bot now using ENTRYPOINT.SH

* Launching the bot now using ENTRYPOINT.SH

* Update ENTRYPOINT.SH

* Update docs for 0.2.0

* Update docs for 0.2.0

* Fix version number

* Updating idna (3.7 -> 3.8)

* The first plugin has prepared basic methods for working with the Outline Server API.

* Added loging and type annotation

* Rename branch and fix actions

* Fix AttributeError: 'list' object has no attribute 'get_secret_value'

* Continue to optimize the code

* Continue to optimize the code

* Update Dockerfile

* Code refactoring

* Added support for bot plugins

* Remove dev code

* refactor: update code in session_manager.py

* refactor: added __all__

* docs: update docker.md and github_registry_install.md

* refactor: --salt arg not needed value

* refactor: remove unused module

* refactor: rewrote and optimized the methods

* refactor: optimization of methods and classes (I have corrected several errors along the way).

* refactor: optimization of methods and classes (I have corrected several errors along the way).

* refactor: _parser.py code optimization

* refactor: global refactoring

* refactor: global refactoring

* refactor: global refactoring

* docs: update all docs

* docs: update README.md and added PLUGINS.md.md

* docs: update docker.md

* feat: monitor plugin added

* feat: monitor plugin added

* feat: update pytmbot.yaml.sample to use latest version of pytmbot

* refactor: change in CI pipeline

* refactor: change in CI pipeline

* deps: pydantic version up and fix app version and description

* chore: fix Dockerfile

* chore: fix Dockerfile

* chore: fix Dockerfile

* chore: fix Dockerfile

* chore: fix Dockerfile

* chore: update CI

* style: Code style improvements

* docs: Update docs

* dep: update dep

* style: Code style improvements

* feat: docker images check update added

* style: Code style improvements

* deps: update dependencies

* feat: update updater module

* style: fix some issues

* fix: some plugins errors fixed

* feat: added more debug information

* style: fix some issues

* deps: update dependencies

* feat: added more debug information

* feat: outline plugin for pytmbot

* dep: update dep

* dep: clean dep list

* style: fix formatting

* feat: Add plugin management system

- Implemented a new system for managing plugins.
- Added methods for registering plugins, fetching plugin names, and descriptions.
- Updated template rendering to display plugin details dynamically.

* feat: Improve plugin handling in handle_plugins function

* chore: Enhance PluginManager with comprehensive documentation

- Added detailed docstrings for PluginManager class and its methods.
- Documented the purpose and usage of each method and attribute.
- Improved error handling descriptions in docstrings.
- Updated _PluginInfo dataclass with attribute descriptions.

* fix: errors in handlers fixed

* docs: update all docs

* docs: update all docs

* docs: added security.md

* chore: code refactoring

* chore: bump version to v0.2.0-rc.1

* chore: reformat code

* docs: update all docs

* docs: update README.md

* chore: remove unused code

* feat: added custom Jinja2 filter

* dep: update emoji (2.12.1 -> 2.13.0) and pytelegrambotapi (4.22.1 -> 4.23.0)

* feat: added emoji in outline plugin

* feat: Added recognition of how the bot is running in a Docker container or not.

* chore: reformat templates

* chore: reformat templates

* chore: added validation into updates.py module

* chore: added expired session cleanup job and Lock in all methods (for security reason)

* docs: update auth_control.md and security.md

* style: fix some errors

* feat: bump version to 0.2.0-rc1